version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  goimports:
    local-prefixes: github.com/mythingies/plugin-webex
